services:
  app_proxy:
    depends_on:
      - server
    environment:
      APP_HOST: server
      APP_PORT: 8900

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 30s
    volumes:
      - ${UMBREL_ROOT}/tor/data:/tor-data:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      UMBREL_ROOT: ${UMBREL_ROOT}
      TOR_DATA_DIR: /tor-data
      ONION_ROTATOR_DRY_RUN: "false"
      ONION_ROTATOR_DEBUG: "false"
