#!/bin/sh
set -eu

settings_file="/data/frigate-settings.env"
config_file="/data/config.toml"
log_file="/data/frigate.log"

if [ -f "$settings_file" ]; then
  set -a
  . "$settings_file"
  set +a
fi

: "${APP_BITCOIN_NODE_IP:=127.0.0.1}"
: "${APP_BITCOIN_RPC_PORT:=8332}"
: "${APP_BITCOIN_ZMQ_SEQUENCE_PORT:=28336}"
: "${FRIGATE_BITCOIN_DATA_DIR:=/data/.bitcoin}"
: "${FRIGATE_BACKEND_ELECTRUM:=}"
: "${FRIGATE_NETWORK:=mainnet}"
: "${FRIGATE_COMPUTE_BACKEND:=CPU}"
: "${FRIGATE_PORT:=57001}"
: "${FRIGATE_BATCH_SIZE:=300000}"
: "${FRIGATE_DB_THREADS:=4}"
: "${FRIGATE_MEMORY_LIMIT:=8GB}"
: "${FRIGATE_CACHE_SIZE:=10M}"
: "${FRIGATE_RPC_TIMEOUT:=60}"
: "${FRIGATE_RPC_BATCH_SIZE:=100}"
: "${FRIGATE_MAX_LABELS:=10}"
: "${FRIGATE_MAX_SUBSCRIPTIONS:=100}"
: "${FRIGATE_START_HEIGHT:=}"

tmp_config="${config_file}.tmp"

{
  printf '# Frigate configuration generated by the Umbrel app settings UI\n'
  printf '[core]\n'
  printf 'connect = true\n'
  printf 'server = "http://%s:%s"\n' "$APP_BITCOIN_NODE_IP" "$APP_BITCOIN_RPC_PORT"
  printf 'authType = "COOKIE"\n'
  printf 'dataDir = "%s"\n' "$FRIGATE_BITCOIN_DATA_DIR"
  if [ -n "$APP_BITCOIN_ZMQ_SEQUENCE_PORT" ]; then
    printf 'zmqSequenceEndpoint = "tcp://%s:%s"\n' "$APP_BITCOIN_NODE_IP" "$APP_BITCOIN_ZMQ_SEQUENCE_PORT"
  fi
  printf 'rpcRequestTimeoutSeconds = %s\n' "$FRIGATE_RPC_TIMEOUT"
  printf 'rpcBatchSize = %s\n' "$FRIGATE_RPC_BATCH_SIZE"
  printf '\n[index]\n'
  if [ -n "$FRIGATE_START_HEIGHT" ]; then
    printf 'startHeight = %s\n' "$FRIGATE_START_HEIGHT"
  fi
  printf 'cacheSize = "%s"\n' "$FRIGATE_CACHE_SIZE"
  printf '\n[scan]\n'
  printf 'batchSize = %s\n' "$FRIGATE_BATCH_SIZE"
  printf 'computeBackend = "%s"\n' "$FRIGATE_COMPUTE_BACKEND"
  printf 'dbThreads = %s\n' "$FRIGATE_DB_THREADS"
  printf 'memoryLimit = "%s"\n' "$FRIGATE_MEMORY_LIMIT"
  printf 'maxLabels = %s\n' "$FRIGATE_MAX_LABELS"
  printf 'maxSubscriptions = %s\n' "$FRIGATE_MAX_SUBSCRIPTIONS"
  printf '\n[server]\n'
  printf 'tcp = "tcp://0.0.0.0:%s"\n' "$FRIGATE_PORT"
  if [ -n "$FRIGATE_BACKEND_ELECTRUM" ]; then
    printf 'backendElectrumServer = "%s"\n' "$FRIGATE_BACKEND_ELECTRUM"
  fi
} > "$tmp_config"

mv "$tmp_config" "$config_file"
chmod 644 "$config_file"
touch "$log_file"
chmod 644 "$log_file"

frigate_bin=""
for candidate in /opt/frigate/bin/frigate /app/bin/frigate /usr/local/bin/frigate /usr/bin/frigate; do
  if [ -x "$candidate" ]; then
    frigate_bin="$candidate"
    break
  fi
done

if [ -z "$frigate_bin" ]; then
  echo "Frigate binary not found in the container image" >> "$log_file"
  exit 1
fi

echo "Starting Frigate with generated configuration at $config_file" >> "$log_file"
exec "$frigate_bin" -d /data -n "$FRIGATE_NETWORK" >> "$log_file" 2>&1
